### ISSUE TITLE
[Critical] Version 1 all playing all videos bring Not found error.

### ISSUE THREAD

**Issue by fdobre** [nexxtv/nexxPLAY-android#8]
nexx-sdk-release-1.16.3

This worked last week perfectly, now all videos do not play and display 'Das Video wurde nicht gefunden`

We cannot make and update to version 2 or 3 in this sprint because it has too many breaking changes.

Please let us know if you need any additional info to help you at debugging.

**Comment by fdobre** [comment]
Hi, the issue could not be replicated anymore in 30 mins after I added this ticket... very strange.

https://cdn-video.bunte.de/584/1548806/0UI5Q1548806LLJ_720x404_900.mp4?fv=1

**Comment by fdobre** [comment]
Before adding this bug we observed that all the videos except (https://cdn-video.bunte.de/584/225528/Z225528K9XQTKES_900_ssc.mp4?fv=1) did not work on Android nexx player.
Very strange, because exactly same videos worked perfectly in IOS player...

Most probably there was an issue on BE side...

**Comment by boredom2** [comment]
Hi there - yes, we had some Server Issues today Morning, but those should be fixed by now and were only affecting the android App.
Please double-check if you use "static" Datamode in your App, as this Method does not need the API and is therefore not affected during any Form of Server Problem.

Additionally - we STRONGLY suggest to update to V3. There are not really many breaking Changes involved, and all other Clients already migrated without any bigger Challenges :)
The main Reason for Updating in your Case is the Support for the new "PlayerStart" Event and the Re-Enabling of Analytics - both Parts are ONLY supported in V2 / V3. Only migrating to a later V1 Version will not really help the BUNTE Guys. Malte will support you as fast as possible, if you face some Migration Issues...

**Comment by fdobre** [comment]
@boredom2 Thank you for the fast response, we were able to build and run v3, I created a new issue related to the remaining issues at upgrade from v1 to v3.
